<?php
"ID": "13",
"KD_BARANG": "BRGU.LG.02.06.E03.0001",
"NM_BARANG": "Test Barang Satu",
"KD_TYPE": "02",
"KD_KATEGORI": "06",
"KD_UNIT": "E03",
"KD_SUPPLIER": "SPL.ESM.00001",
"KD_DISTRIBUTOR": "null",
"PARENT": "null",
"HPP": 6,
"HARGA": 4,
"BARCODE": "null",
"IMAGE": "null",
"NOTE": "dummy coba data",
"KD_CORP": "LG",
"KD_CAB": "null",
"KD_DEP": "null",
"STATUS": 1,
"CREATED_BY": "piter@lukison.com",
"CREATED_AT": "2015-12-19 20:09:35",
"UPDATED_BY": "alam@lukison.com",
"UPDATED_AT": "2016-01-25 09:11:10",
"DATA_ALL": "null",
"CORP_ID": null