<?php

"ID": "1",
"KD_SUPPLIER": "SPL.ESM.00001",
"NM_SUPPLIER": "PT. MAXINDO KARYA ANUGERAH",
"ALAMAT": "Jl. Olympic Raya Blok B-11 Kawasan Industri Sentul\r\nBabakan Madang-Bogor",
"KOTA": "Bogor",
"TLP": "021 87900305",
"MOBILE": "",
"FAX": "021 87904683",
"PIC": null,
"EMAIL": "irene.maxichips@yahoo.co.id",
"WEBSITE": "",
"IMAGE": null,
"NOTE": "",
"KD_CORP": "ESM",
"KD_CAB": null,
"KD_DEP": null,
"STATUS": 1,
"CREATED_BY": "adel",
"CREATED_AT": "2015-09-29 07:03:36",
"UPDATED_BY": null,
"UPDATED_AT": null,
"DATA_ALL": null